---
# w&b
project_name: 'CANCER'
name: 'run_1'
group: 'brain'

# dataset
train_dir: 'train_brain.csv'
valid_dir: 'val_brain.csv'
aug: 'geometric'

# model
# model: 'resnet18'
epochs: 50
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.0005
scheme: False

# weights

save_dir: './weights/brain/'
workers: 2
fp16: None
device: 'mps'
