---
# w&b
project_name: 'TUMOR_DETECTION'
name: 'network_3_convs_2_fc'
group: 'brain'
mode: 'disabled'

# dataset
train_dir: 'train_brain.csv'
valid_dir: 'val_brain.csv'
aug: 'geometric'

# model
# model: 'resnet18'
epochs: 50
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.0005
scheme: False

# weights

save_dir: './weights/brain/'
# workers: 
# fp16: None
device: 'mps'
